### ISSUE TITLE
Large image size?

### ISSUE THREAD

**Issue by kk-hainq** [jkachmar/alpine-haskell-stack#6]
I might be doing it wrong here but after building both `alpine-haskell-gmp` and `alpine-haskell-simple` on my machine, the result images are quite larger than a standard image built on top of `debian`. Built images when I bump the base image to `alpine:3.10.1` and `stack` to `2.1.3`:

```
alpine-haskell-simple  8.6.5            8085be6b0318  1.98GB
alpine-haskell-simple  build-tooling    deb0f50d9977  151MB
alpine-haskell-simple  build-ghc-8.6.5  7f740dc48330  2.98GB
alpine-haskell-simple  base             2eedfb0ac8eb  121MB

alpine-haskell-gmp     8.6.5            38f62343dd94  1.98GB
alpine-haskell-gmp     build-tooling    a08d1803194e  153MB
alpine-haskell-gmp     build-ghc-8.6.5  e8257ef09cdf  2.98GB
alpine-haskell-gmp     base             bc0ba3d8334f  122MB
```
Removing `cabal-install` and bumping `stack` to `2.1.3` from [this Dockerfile](https://github.com/freebroccolo/docker-haskell/blob/master/8.6/Dockerfile) yields an 1.15GB image. The gap between the compressed versions isn't as bad but shouldn't we expect a better size for images built on top of `alpine`?

Thank you again for a good reference! This is just a question out of curiosity.

**Comment by symbiont-joseph-kachmar** [comment]
These images are, unfortunately, going to be quite large as they're going to include the development and compilation environment you need to produce Haskell applications under Alpine.

The intended purpose here is _not_ for you to ship applications that run in these images, but for you to use these images as a "builder" for a multi-stage docker build. That way you can make your final step something like:
```Dockerfile
FROM alpine-haskell-gmp:8.6.5 as builder
RUN <install OS dependencies>
RUN <build application>

FROM alpine:3.9
COPY --from=builder <path/to/application>
RUN <install OS dependencies>
ENTRYPOINT [<run app>]
```

In this case, the final image should be quite small (it should just be the Alpine image + OS dependencies + your Haskell application.

Does this make sense?

**Comment by kk-hainq** [comment]
Thanks for the clarification and yes, it does make sense.

I think our problem is that we're having 7 different Haskell services that need dev images with things like hot-reload included so the dev images are even more important at the moment. On top of `debian`, our compressed prod images are still only 50MB-75MB with dev images going up to over 850MB (over 4GB uncompressed). Adding an extra uncompressed 800MB for each dev images would be very scary.

Now that I've got your confirmation (that the build images are correctly large, not that I built them wrong), I think we can try developing on top of `debian` and testing, shipping a version on top of `alpine` in the future. We would need to scale a ton more to make the differences and extra mismatches worth it though.

Thanks again for your time, this issue should be closed now!

**Comment by symbiont-joseph-kachmar** [comment]
Thanks for the extra info!

I'm hopeful that future versions of GHC will ship with a binary distribution that targets Alpine, which would obviate a lot of this work, so hopefully by the time you've scaled up this shouldn't be necessary at all 😄
